### ISSUE TITLE
Support for scoped packages?

### ISSUE THREAD

**Issue by FredyC** [franciscop/legally#14]
With version 2.8.1 I am getting crash for [scoped packages](https://docs.npmjs.com/misc/scope).

> Error: Cannot find module 'D:\workspace\app/node_modules/@kadira/package.json'

It should recognize scoped package folder (prefixed with @) and check for modules in there instead of looking for a package.json.

**Comment by eladnava** [comment]
PR submitted. 👍

**Comment by franciscop** [comment]
You can check it now with legally >= 2.9 (just reinstall it and it should be good to go) thanks to @eladnava :+1:

**Comment by eladnava** [comment]
My pleasure! 👍

**Comment by electrified** [comment]
Scoped packages which are dependent on other scoped packages still seem to result in an error? 
`Error: Cannot find module '/Users/ebr04/Documents/skybet/bet-webapp/node_modules/@skybetintl/ui-promotions/node_modules/@skybetintl/package.json'`
