### ISSUE TITLE
Exclude devDependencies

### ISSUE THREAD

**Issue by michelwilson** [franciscop/legally#28]
Is there a way to exclude dev dependencies? If I understand the legality of it correctly, this is useful when using webpack. Dev dependencies are only used when _making_ the build, they are not part _of_ the build, and so can be ignored when not distributing the build, but only the result of the build.

**Comment by franciscop** [comment]
Not directly, BUT you can do:

```
rm -rf node_modules
npm install --only=prod
legally
npm install
```
