### ISSUE TITLE
Feature request: check which licenses are incompatible

### ISSUE THREAD

**Issue by dbkaplun** [franciscop/legally#3]

**Comment by franciscop** [comment]
Could you expand please? Do you mean if a package has two different licenses? Or check each license against another? This looks like it might become a combination impossibility.

**Comment by dbkaplun** [comment]
I meant comparing the current project's license against all of its dependencies to see if there are any incompatibilities. Most open-source licenses should be compatible with each other so I don't know how useful this will be but I think ianal should have a feature like this.

**Comment by franciscop** [comment]
A similar but not the same would be in the options now as `--type` filter:

```bash
legally --type mit
```

**Comment by franciscop** [comment]
And for the original request, I am not a lawyer as displayed in the Readme and I don't have the resources/capacity to check for compatibility for the licenses, so I close this
