### ISSUE TITLE
default parameter error in node < 6

### ISSUE THREAD

**Issue by chrisweb** [franciscop/legally#7]
[Nodejs 6 has support for default parameters](https://github.com/nodejs/node/issues/3070#issuecomment-218908400) but not earlier versions

your code has a least one default parameter that generates an error in node < 6:

```javascript
node_modules\legally\lib\license.js:6
module.exports = function(text, def = []){
                                    ^
SyntaxError: Unexpected token =
```

For example here at my workplace I still use a node 4 LTS (https://github.com/nodejs/LTS#lts-schedule) which does not yet (nativly) support default parameters

I would suggest adding a the engines field to the package json 

`{ "engines" : { "node" : ">=6.0.0" } }`

or use babel / typescript to compile an ES5 version of the code 
or remove the default parameters until all the node LTS < 6 have reached their "end of life / maintenance" date

**Comment by franciscop** [comment]
Thanks, should be fixed in V2.8.0
