### ISSUE TITLE
warning if conflicting licenses get detected

### ISSUE THREAD

**Issue by chrisweb** [franciscop/legally#8]
What would be really great (in my opinion) would be if legally could emit warnings if it detects that you are about to use packages that have a license which is not ["compatible"](https://en.wikipedia.org/wiki/License_compatibility) with your own project license ... The best resource I could find so far is [the page of the free software foundation](https://www.gnu.org/licenses/license-list.en.html) about licenses compatibility (the is more in their [wiki](http://gplv3.fsf.org/wiki/index.php/Compatible_licenses) and on their [FAQ](https://www.gnu.org/licenses/gpl-faq.html) page). I also found [a chart on wikipedia](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses) comparing open source licenses and showing which one are compatible with the GPLv3 and which not.

You can close this after reading, as I don't think this is doable right now and without the help of a bunch of legal advisors :( but as stated on the [apache foundation GPL-compatibility page](https://www.apache.org/licenses/GPL-compatibility.html), maybe the [software freedom law center](http://www.softwarefreedom.org/) might be able to help out!?

**Comment by franciscop** [comment]
This would be nice but I do not plan on implementing this for the complexity but feel free to send a PR with this functionality.

**Comment by franciscop** [comment]
Also, this is a duplicate, check https://github.com/franciscop/legally/issues/3
