### ISSUE TITLE
Commercial license checking

### ISSUE THREAD

**Issue by eladnava** [franciscop/legally#9]
Hi there,
Loving the package! Thanks so much for all the work you put into this. This really makes license checking a breeze in comparison to other packages. 

I really like the summary view!

I think it would be great if we could run `legally --commercial` and have legally warn us about any dependencies whose licenses prohibit commercial-use (since this is probably the number one reason people check licenses).

We could use the following website to check (in advance) which licenses prohibit commercial use:
https://tldrlegal.com

What do you think about this? Looking forward to hearing your thoughts.

**Comment by franciscop** [comment]
Thanks, this would be nice and would be a great addition, but I think that implementing this would be a similar task that the whole project so I do not plan on adding something like this anytime soon. Would you like to develop this?

**Comment by eladnava** [comment]
Thanks for your response! At the moment I don't think I'll find the time to complete this though.

Do you think this should be part of `legally` or an external module that makes use of `legally`?

**Comment by franciscop** [comment]
Both are possible, but `legally` is not built in a way that allows for easy extension (but it does allow for easy modification) as it's a public-facing tool, not a library.

And that is the basic reason why I created `legally`, to check (and avoid) for commercial and share-alike licenses. I've read enough about compatibility, besides what I search when I don't know it, to love MIT while disliking the GPL so for me that's enough. However, ideally this would be a commercial, share alike, attribution, etc checker.

**Comment by eladnava** [comment]
I see. Yeah, I've done the same research, but every once in a while you end up with a package using some weird, uncommon license (i.e. `AFL 2.1` / `CC0` / `CC BY 4.0`) and it would be nice to know immediately how restrictive that license is.

Anyhow, I'll see if I find the time to develop anything like this and let you know if I do.

**Comment by eladnava** [comment]
@franciscop I went ahead and developed this! 😁 

It's called [tldrlegal](https://github.com/eladnava/tldrlegal) and it provides the following output, using legally to both determine the dependencies' licenses and build the output tables:

![Preview](https://raw.github.com/eladnava/tldrlegal/master/assets/output.png) 

Check it out and let me know what you think! 👍

**Comment by franciscop** [comment]
That is... really awesome!! I knew that making my projects modular would help someone some day, I see your `var legally = require('legally/lib/legally');` which returns the packages with their licenses even though it is not documented. I will add your project to the readme of legally.

One of the main features for `legally` is to be able to check a package before installing it with `legally PACKAGENAME`. I do it based on [`minimist`](https://www.npmjs.com/package/minimist) as can be seen [here](https://github.com/franciscop/legally/blob/master/index.js) and [here (remote package installation in temp folder)](https://github.com/franciscop/legally/blob/master/lib/remote.js), in case you are considering it.

**Comment by eladnava** [comment]
@franciscop Glad you like it! 😄 

Yeah, I found the "unofficial" API extremely easy to use, thanks for making it so modular! The table generator is also awesome.

Regarding remote checking, that's cool! I'll consider adding it in the future to `tldrlegal` as well :10

**Comment by eladnava** [comment]
@franciscop FYI I also wrote a blog post and mentioned legally :)
https://eladnava.com/check-your-dependencies-license-requirements-with-tldrlegal/
